name: go test darwin

on: [pull_request, workflow_dispatch]

env:
  DYLD_LIBRARY_PATH: /opt/senzing/er/lib:/opt/senzing/er/lib/macos
  LD_LIBRARY_PATH: /opt/senzing/er/lib:/opt/senzing/er/lib/macos
  SENZING_TOOLS_DATABASE_URL: "sqlite3://na:na@/tmp/sqlite/G2C.db"

permissions:
  contents: read

jobs:
  go-test-darwin:
    name: "go test with Senzing: ${{ matrix.senzingapi-version }}; OS: ${{ matrix.os }}; Go: ${{ matrix.go }}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go: ["1.21"]
        os: [macos-13]
        senzingapi-version: [staging-v4]

    steps:
      - name: checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: setup go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - name: install Senzing API
        uses: senzing-factory/github-action-install-senzing-api@v3
        with:
          senzingapi-version: ${{ matrix.senzingapi-version }}

      - name: copy /etc files
        run: sudo cp testdata/senzing-license/g2.lic /opt/senzing/er/etc/g2.lic

      - name: copy test database files
        run: mkdir /tmp/sqlite && cp testdata/sqlite/G2C.db /tmp/sqlite/G2C.db

      - name: run go test
        run: go test -exec /Users/runner/work/go-helpers/go-helpers/bin/macos_exec_dyld.sh -v -p 1 -coverprofile=./cover.out -covermode=atomic -coverpkg=./... ./...

      - name: Store coverage file
        uses: actions/upload-artifact@v4
        with:
          name: cover.out
          path: ./cover.out

  coverage:
    name: coverage
    needs: go-test-darwin
    uses: senzing-factory/build-resources/.github/workflows/go-coverage.yaml@v2
