name: Go test darwin

on: [pull_request, workflow_dispatch]

env:
  SENZING_LOG_LEVEL: TRACE
  SENZING_TOOLS_DATABASE_URL: sqlite3://na:na@nowhere/tmp/sqlite/G2C.db

permissions:
  contents: read

jobs:
  go-test-darwin:
    name: "Go test with Senzing: ${{ matrix.senzingsdk-version }}; OS: ${{ matrix.os }}; Go: ${{ matrix.go }}"
    runs-on: ${{ matrix.os }}
    env:
      SENZING_PATH: /Users/runner/senzing
      DYLD_LIBRARY_PATH: "/Users/runner/senzing/er/lib:/Users/runner/senzing/er/lib/macos"
      LD_LIBRARY_PATH: "/Users/runner/senzing/er/lib:/Users/runner/senzing/er/lib/macos"
    strategy:
      matrix:
        go: ["1.21"]
        os: [macos-latest]
        senzingsdk-version: [staging-v4]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - name: Set up gotestfmt
        uses: gotesttools/gotestfmt-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Senzing SDK
        uses: senzing-factory/github-action-install-senzing-sdk@v3
        with:
          senzingsdk-repository-path: ${{ secrets.SENZING_OSX_BETA_REPOSITORY }}

      - name: Echo environment variables 1
        run: |
          echo "SENZING_PATH ${SENZING_PATH}"
          echo "DYLD_LIBRARY_PATH ${DYLD_LIBRARY_PATH}"
          echo "LD_LIBRARY_PATH ${LD_LIBRARY_PATH}"

      - name: Export variables
        run: |
          export SENZING_PATH="${HOME}/senzing"
          export DYLD_LIBRARY_PATH="${SENZING_PATH}/er/lib:${SENZING_PATH}/er/lib/macos"
          export LD_LIBRARY_PATH="${SENZING_PATH}/er/lib:${SENZING_PATH}/er/lib/macos"
          echo "HOME ${HOME}"
          echo "SENZING_PATH ${SENZING_PATH}"
          echo "DYLD_LIBRARY_PATH ${DYLD_LIBRARY_PATH}"
          echo "LD_LIBRARY_PATH ${LD_LIBRARY_PATH}"

      - name: Echo environment variables 2
        run: |
          echo "SENZING_PATH ${SENZING_PATH}"
          echo "DYLD_LIBRARY_PATH ${DYLD_LIBRARY_PATH}"
          echo "LD_LIBRARY_PATH ${LD_LIBRARY_PATH}"

      - name: Copy /etc files
        run: sudo mkdir -p "${SENZING_PATH}/er/etc" && sudo cp testdata/senzing-license/g2.lic "${SENZING_PATH}/er/etc/g2.lic"

      - name: Copy test database files
        run: mkdir -p /tmp/sqlite && cp testdata/sqlite/G2C.db /tmp/sqlite/

      - name: Run go test
        run: go test -exec "${GITHUB_WORKSPACE}/bin/macos_exec_dyld.sh" -json -v -p 1 -coverprofile=./cover.out -covermode=atomic -coverpkg=./... ./...  2>&1 | tee /tmp/gotest.log | gotestfmt

      - name: Store coverage file
        uses: actions/upload-artifact@v4
        with:
          name: cover.out
          path: ./cover.out

      - name: Upload test log
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-log
          path: /tmp/gotest.log
          if-no-files-found: error

  coverage:
    name: Coverage
    needs: go-test-darwin
    uses: senzing-factory/build-resources/.github/workflows/go-coverage.yaml@v2
    with:
      coverage-config: ./.github/coverage/testcoverage.yaml
